Repository data-automation-framework/daf-meta, pull requests merged in 2021-04, with the labels that each got.

#14 Fixed app crashing when the stored MetadataPath is invalid on launch
  Daf.Meta.Editor/ViewModels/MainViewModel.cs
Labels: bug

#2 Implemented view models for Connections window
  Daf.Meta.Editor/Messages.cs
  Daf.Meta.Editor/ViewModels/ColumnViewModel.cs
  Daf.Meta.Editor/ViewModels/ConnectionViewModel.cs
  Daf.Meta.Editor/ViewModels/ConnectionViewModels/GraphQlConnectionViewModel.cs
  Daf.Meta.Editor/ViewModels/ConnectionViewModels/MySqlConnectionViewModel.cs
  Daf.Meta.Editor/ViewModels/ConnectionViewModels/OdbcConnectionViewModel.cs
  Daf.Meta.Editor/ViewModels/ConnectionViewModels/OleDBConnectionViewModel.cs
  Daf.Meta.Editor/ViewModels/ConnectionViewModels/RestConnectionViewModel.cs
  Daf.Meta.Editor/ViewModels/ConnectionsViewModel.cs
  Daf.Meta.Editor/ViewModels/DataWarehouseViewModel.cs
  Daf.Meta.Editor/ViewModels/MainViewModel.cs
  Daf.Meta.Editor/ViewModels/StagingColumnViewModel.cs
  Daf.Meta/Layers/Connections/GraphQlConnection.cs
  Daf.Meta/Layers/Connections/MySqlConnection.cs
  Daf.Meta/Layers/Connections/OdbcConnection.cs
  Daf.Meta/Layers/Connections/OleDBConnection.cs
  Daf.Meta/Layers/Connections/RestConnection.cs
  Daf.Meta/Model.cs
Labels: enhancement

#36 Implemented exit click event from File menu for Datawarehouse, Connections, SourceSystems and Tenants Windows
  Daf.Meta.Editor/Windows/ConnectionsWindow.xaml
  Daf.Meta.Editor/Windows/ConnectionsWindow.xaml.cs
  Daf.Meta.Editor/Windows/DataWarehouseWindow.xaml
  Daf.Meta.Editor/Windows/DataWarehouseWindow.xaml.cs
  Daf.Meta.Editor/Windows/SourceSystemsWindow.xaml
  Daf.Meta.Editor/Windows/SourceSystemsWindow.xaml.cs
  Daf.Meta.Editor/Windows/TenantsWindow.xaml
  Daf.Meta.Editor/Windows/TenantsWindow.xaml.cs
Labels: bug

#38 Implemented View Models for Tenants
  Daf.Meta.Editor/Messages.cs
  Daf.Meta.Editor/ViewModels/MainViewModel.cs
  Daf.Meta.Editor/ViewModels/TenantViewModel.cs
  Daf.Meta.Editor/ViewModels/TenantsViewModel.cs
Labels: enhancement

#37 Implemented View Models for Source Systems
  Daf.Meta.Editor.Tests/HubsViewModelTests.cs
  Daf.Meta.Editor/Messages.cs
  Daf.Meta.Editor/ViewModels/MainViewModel.cs
  Daf.Meta.Editor/ViewModels/SourceSystemViewModel.cs
  Daf.Meta.Editor/ViewModels/SourceSystemsViewModel.cs
  Daf.Meta.Editor/Windows/SourceSystemsWindow.xaml
Labels: enhancement

#41 Push nuget packages to nuget.org instead of Github packages
  .github/workflows/release.yml
Labels: create-release

#43 Added scrollviewer to HubRelationshipControl
  Daf.Meta.Editor/UserControls/HubRelationshipControl.xaml
  Daf.Meta.Editor/UserControls/LinkRelationshipControl.xaml
Labels: bug

#39 Build using latest patch version of .NET
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: enhancement

#45 Added property for target platform assembly version
  Daf.Meta/DataWarehouse.cs
  Daf.Meta/Enums.cs
Labels: create-release, enhancement

#42 Implemented View Model for HubRelationship
  Daf.Meta.Editor/Messages.cs
  Daf.Meta.Editor/UserControls/HubRelationshipsControl.xaml
  Daf.Meta.Editor/UserControls/HubRelationshipsControl.xaml.cs
  Daf.Meta.Editor/ViewModels/HubRelationshipViewModel.cs
  Daf.Meta.Editor/ViewModels/HubRelationshipsViewModel.cs
  Daf.Meta.Editor/ViewModels/HubViewModel.cs
  Daf.Meta.Editor/ViewModels/HubsViewModel.cs
  Daf.Meta.Editor/ViewModels/MainViewModel.cs
  Daf.Meta/Layers/BusinessKey.cs
  Daf.Meta/Layers/BusinessKeyEventArgs.cs
  Daf.Meta/Layers/HubRelationship.cs
  Daf.Meta/Model.cs
Labels: create-release
